name: List Repo

on:
  workflow_call:
    inputs:
      directory_path:
        description: "Caminho do diretório"
        type: string
        required: true

jobs:
  check-repo:
    runs-on: ubuntu-latest
    outputs:
      saida: ${{ steps.list-repo }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: List repo
        id: list-repo
        run: ls ${{ inputs.directory_path }}
